# -*- coding: utf-8 -*-
"""gearbox_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwSaJTwcznCBY9Zd83OS85oSgGeU7YFC
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("gearbox_failure.pkl")

st.title("Gearbox Failure Prediction")

# Input fields
load = st.number_input("Load_%")
temp = st.number_input("Temperature_C")
vibra = st.number_input("Vibration_mm_s")
oil = st.number_input("Oil_Level_%")


df = pd.DataFrame({
    "Load_%": [load],
    "Temperature_C": [temp],
    "Vibration_mm_s": [vibra],
    "Oil_Level_%": [oil]
})

if st.button("Predict Failure"):
    prediction = model.predict(df)
    if prediction[0] == 1:
        st.error(f"Gearbox Failure Prediction!")
    else:
        st.success("Gearbox Failure not Predicted")